FROM docker.elastic.co/elasticsearch/elasticsearch:6.1.1
LABEL maintainer Sybren A. Stüvel <sybren@blender.studio>

RUN elasticsearch-plugin remove --purge  x-pack

ADD elasticsearch.yml jvm.options /usr/share/elasticsearch/config/

USER root
RUN chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/config/
USER elasticsearch
