FROM docker.elastic.co/kibana/kibana:5.6.1
LABEL maintainer Sybren A. Stüvel <sybren@blender.studio>

RUN bin/kibana-plugin remove x-pack
ADD kibana.yml /usr/share/kibana/config/kibana.yml
RUN kibana 2>&1 | grep -m 1 "Optimization of .* complete"
