mongo:
  image: mongo
  container_name: mongo
  restart: always
  volumes:
   - /data/storage/db:/data/db
  ports:
   - "127.0.0.1:27017:27017"
redis:
  image: redis
  container_name: redis
  restart: always
blender_cloud:
  image: armadillica/blender_cloud:latest-py36
  container_name: blender_cloud
  restart: always
  environment:
   VIRTUAL_HOST: http://cloudapi.blender.org/*,https://cloudapi.blender.org/*,http://cloud.blender.org/*,https://cloud.blender.org/*,http://pillar-web/*
   VIRTUAL_HOST_WEIGHT: 10
   FORCE_SSL: "true"
  volumes:
   - /data/git:/data/git:ro
   - /data/config:/data/config:ro
   - /data/storage/pillar:/data/storage/pillar
  links:
   - mongo
   - redis
# notifserv:
#   container_name: notifserv
#   image: armadillica/pillar-notifserv:cd8fa678436563ac3b800b2721e36830c32e4656
#   restart: always
#   links:
#    - mongo
#   environment:
#    VIRTUAL_HOST: https://cloud.blender.org/notifications*,http://pillar-web/notifications*
#    VIRTUAL_HOST_WEIGHT: 20
#    FORCE_SSL: true
grafista:
  image: armadillica/grafista
  container_name: grafista
  restart: always
  environment:
    VIRTUAL_HOST: http://cloud.blender.org/stats/*,https://cloud.blender.org/stats/*,http://blender-cloud/stats/*
    VIRTUAL_HOST_WEIGHT: 20
    FORCE_SSL: "true"
  volumes:
    - /data/git/grafista:/data/git/grafista:ro
    - /data/storage/grafista:/data/storage
haproxy:
  image: dockercloud/haproxy
  container_name: haproxy
  restart: always
  ports:
   - "443:443"
   - "80:80"
  environment:
   - CERT_FOLDER=/certs/
   - TIMEOUT=connect 5s, client 5m, server 10m
  links:
   - blender_cloud
   - grafista
   # - notifserv
  volumes:
   - '/data/certs:/certs'
